.github/workflows/export-types.yml

[DOPS-1495]: Polkaswap: Implement: automatic commit types updates.
1. Add automatic commit types updates.
Signed-off-by: Pavel Varfolomeev  wpi86@yandex.ru>
[DOPS-1495]: https://soramitsu.atlassian.net/browse/DOPS-1495

[DOPS-1495]: Polkaswap: Implement: automatic commit types updates.

---

.github/workflows/export-types.yml

[DOPS-1495]: Fix yarn install
1. fix yarn install
Signed-off-by: Pavel Varfolomeev  wpi86@yandex.ru>
[DOPS-1495]: https://soramitsu.atlassian.net/browse/DOPS-1495

[DOPS-1495] Fix yarn install

---

.github/workflows/export-types.yml

[DOPS-1495]: Fix env names
1. Fix env names
2. Add dispatch start
Signed-off-by: Pavel Varfolomeev  wpi86@yandex.ru>
[DOPS-1495]: https://soramitsu.atlassian.net/browse/DOPS-1495

Fix env names

---

.github/workflows/export-types.yml

[DOPS-1495]: Fix autocommit
1. Change description
2. Add reviewers
Signed-off-by: Pavel Varfolomeev  wpi86@yandex.ru>
[DOPS-1495]: https://soramitsu.atlassian.net/browse/DOPS-1495

Fix autocommit

---

.github/workflows/export-types.yml

Fix autocommit config

---

.github/workflows/export-types.yml

[DOPS-1495]: Add pr url
1. Add pr url.
Signed-off-by: Pavel Varfolomeev wpi86@yandex.ru

Add pr url

---

Jenkinsfile

[DOPS-1576]: Update the NPM login function in the Jenkins JS library.
1. Update Jenkinsfile.
Signed-off-by: Dmitriy Creed <creed@soramitsu.co.jp>
[DOPS-1576]: https://soramitsu.atlassian.net/browse/DOPS-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOPS-1576] Update the NPM login function in the jenkins JS library

---

.npmrc

[DOPS-1593]: Auto PR creation is broken for types in sora2-substrate-js-library
1. Delete .npmrc file
2. Token generation and substitution occurs in the MainPipeline
Signed-off-by: Nikita Zaporozhets <zaporozhets@soramitsu.co.jp>
[DOPS-1593]: https://soramitsu.atlassian.net/browse/DOPS-1593

[DOPS-1593]: Auto PR creation is broken for types in sora2-substrate-js-library

---

.github/workflows/export-types.yml

[DOPS-1967]: Check types auto-update
1. Remove Pavel Golovkin from workflow
Signed-off-by: name <zaporozhets@soramitsu.co.jp>
[DOPS-1967]: https://soramitsu.atlassian.net/browse/DOPS-1967

[DOPS-1967]: Check types auto-update

---

Jenkinsfile

Set appropriate sonarProjectKey

DOPS-2382 Update sonarProjectKey

---

packages/api/package.json
packages/liquidity-proxy/package.json
packages/liquidity-proxy/src/quote/xst.ts
packages/math/package.json
packages/type-definitions/package.json
packages/types/package.json
packages/types/src/interfaces/augment-api-errors.ts
packages/types/src/interfaces/lookup.ts
packages/types/src/interfaces/types-lookup.ts
packages/types/src/metadata/stage/types_scalecodec_mobile.json
packages/types/src/metadata/stage/types_scalecodec_python.json
packages/util/package.json

https://github.com/sora-xor/sora2-network/pull/423

Xst fixes from backend

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/liquidity-proxy/src/quote/xst.ts
packages/math/package.json
packages/type-definitions/package.json
packages/types/package.json
packages/types/src/interfaces/augment-api-consts.ts
packages/types/src/interfaces/augment-api-events.ts
packages/types/src/interfaces/augment-api-query.ts
packages/types/src/interfaces/augment-api-tx.ts
packages/types/src/interfaces/lookup.ts
packages/types/src/interfaces/types-lookup.ts
packages/util/package.json

https://github.com/sora-xor/sora2-network/pull/660

XST update 

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/liquidity-proxy/src/consts.ts
packages/liquidity-proxy/src/index.ts
packages/liquidity-proxy/src/pallets/liquidityProxy/index.ts
packages/liquidity-proxy/src/pallets/poolXyk/index.ts
packages/liquidity-proxy/src/types.ts
packages/math/package.json
packages/type-definitions/package.json
packages/types/package.json
packages/util/package.json
packages/util/src/assets/index.ts
packages/util/src/swap/index.ts

https://github.com/sora-xor/sora2-network/pull/1078

Chameleon quote limits

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/math/package.json
packages/type-definitions/package.json
packages/types/package.json
packages/util/package.json
packages/util/src/bridgeProxy/index.ts
packages/util/src/bridgeProxy/methods.ts
packages/util/src/bridgeProxy/sub/consts.ts
packages/util/src/bridgeProxy/sub/index.ts
packages/util/src/bridgeProxy/sub/types.ts

* update getAccount method
* update bridge proxy networks relations
* bump version
* set 1.39.1
* add SubEvmNetwork type

Bridge proxy updates (#861)

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/liquidity-proxy/src/pallets/multicollateralBoundingCurvePool.ts
packages/math/package.json
packages/type-definitions/package.json
packages/types/package.json
packages/util/package.json

https://github.com/sora-xor/sora2-network/pull/1121

[ALT] TBC step quote

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/math/package.json
packages/type-definitions/package.json
packages/types/package.json
packages/util/package.json
packages/util/src/storage.ts

* updated_storage_with_event
* version_updated

Feature/updated storage event (#868)

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/liquidity-proxy/src/common/primitives.ts
packages/liquidity-proxy/src/pallets/liquidityProxy/liquidityAggregator/selector.ts
packages/liquidity-proxy/src/pallets/liquidityProxy/smartSplit.ts
packages/math/package.json
packages/type-definitions/package.json
packages/types/package.json
packages/util/package.json

https://github.com/sora-xor/sora2-network/pull/1153

step quote verification

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/liquidity-proxy/src/pallets/liquidityProxy/index.ts
packages/liquidity-proxy/src/pallets/poolXyk/utils.ts
packages/liquidity-proxy/src/runtime/index.ts
packages/math/package.json
packages/type-definitions/package.json
packages/types/package.json
packages/util/package.json
packages/util/src/poolXyk/index.ts
packages/util/src/swap/index.ts

https://github.com/sora-xor/sora2-network/pull/1187

Disable chameleon pools

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/math/package.json
packages/sdk/package.json
packages/sdk/src/assets/consts.ts
packages/type-definitions/package.json
packages/types/package.json

- _Add field to consts._
- _For filtering in UI._
---
---

add field to consts

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/math/package.json
packages/sdk/package.json
packages/sdk/src/extendedAssets/index.ts
packages/sdk/src/extendedAssets/types.ts
packages/type-definitions/package.json
packages/types/package.json

- _Add method for fetching address._
- _Part of the functionality to allow/forbid to send to non-SBT owner._
---
---
- Issue/Task link: _[PW-1715](https://soramitsu.atlassian.net/browse/PW-1715?atlOrigin=eyJpIjoiNzk2YzE0MWFiOTdmNGUwZThkZjUzZDkwNDcxYTFlZDkiLCJwIjoiaiJ9)_
---

[PW-1715] Feature/add sbt address fetch

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/math/package.json
packages/sdk/package.json
packages/sdk/src/dex/consts.ts
packages/sdk/src/swap/index.ts
packages/type-definitions/package.json
packages/types/package.json

[Fix] order book for vxor

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/liquidity-proxy/src/consts.ts
packages/math/package.json
packages/sdk/package.json
packages/type-definitions/package.json
packages/types/package.json

Add vxor to order book liquidity proxy

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/math/package.json
packages/sdk/package.json
packages/sdk/src/assets/consts.ts
packages/type-definitions/package.json
packages/types/package.json

- Added VXOR to consts
- Because in new Point System we are using VXOR
---
---
---
---
---
---

added_vxor_to_consts

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/math/package.json
packages/sdk/package.json
packages/type-definitions/package.json
packages/types/package.json
packages/types/src/interfaces/augment-api-query.ts

update types from chain

---

doc.md
packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/math/package.json
packages/sdk/package.json
packages/sdk/src/BaseApi.ts
packages/sdk/src/system/index.ts
packages/sdk/src/types.ts
packages/type-definitions/package.json
packages/types/package.json
packages/types/src/interfaces/augment-api-events.ts
packages/types/src/interfaces/lookup.ts
packages/types/src/interfaces/types-lookup.ts
packages/types/src/metadata/dev/types_scalecodec_mobile.json
packages/types/src/metadata/dev/types_scalecodec_python.json
packages/types/src/metadata/prod/types_scalecodec_mobile.json
packages/types/src/metadata/prod/types_scalecodec_python.json
packages/types/src/metadata/stage/types_scalecodec_mobile.json
packages/types/src/metadata/stage/types_scalecodec_python.json
packages/types/src/metadata/test/types_scalecodec_mobile.json
packages/types/src/metadata/test/types_scalecodec_python.json

- _I've added an extrinsic for SORATOPIA project_
- _So it'll be easier to integrate it into SORATOPIA itself_
---
---
- _It should work fine from scripts_
- _NetworkFee should have a fee for the SORATOPIA checkin_
---

Add SORATOPIA checkin

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/liquidity-proxy/src/consts.ts
packages/math/package.json
packages/sdk/package.json
packages/type-definitions/package.json
packages/types/package.json

update XYK fee to 0.6%

---

packages/api/package.json
packages/connection/package.json
packages/liquidity-proxy/package.json
packages/math/package.json
packages/sdk/package.json
packages/type-definitions/package.json
packages/types/package.json

up version
